- name: "Send website - Phase1: Initialize Directories"
  ansible.builtin.file:
    path: "/var/www/html/{{ item }}"
    state: directory
    mode: "755"
  loop: "{{ website_directories }}"
  listen: "Send_website"

- name: "Send website - Phase2: Send static Files"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/www/html/{{ item }}"
    mode: "644"
  loop: "{{ website_static_files }}"
  listen: "Send_website"
  notify: Service Restart

- name: "Send website - Phase3: Send dynamic Files"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/var/www/html/{{ item }}"
    mode: "644"
  loop: "{{ website_dynamic_files }}"
  listen: "Send_website"
  notify: Service Restart

- name: Service Restart
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: restarted
