- name: Installing webserver
  ansible.builtin.apt:
    name: "{{ package_name }}"
    update_cache: true
    state: present
  notify: "Send_website"
  register: status
  changed_when: not status.failed
  when: ansible_facts.os_family == "Debian"
